### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by JiYou** [exmex/KingdomRushFrontiers#1]
```
CMake Error at CMakeLists.txt:117 (add_executable):
  Cannot find source file:

    Classes/HelloWorldScene.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

I can not find Classes/HelloWorldScene.h and `Classes/HelloWorldScene.cpp` files.
are they  missing?

**Comment by exmex** [comment]
This project is not configured to use CMake. Either edit the CMake file yourself, or just use the provided solution

**Comment by Round0house** [comment]
> This project is not configured to use CMake. Either edit the CMake file yourself, or just use the provided solution

I cant figure out how to build it, can you please expand on the provided solution you mentioned?

**Comment by exmex** [comment]
Just dont use CMake and build using the solution file located here:

proj.win32/KingdomRush.sln
